### ISSUE TITLE
Changing the content of catalog.xml should refresh catalogs and trigger validation

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#212] opened 2018-11-09 16:14 UTC
Changing the content of catalog.xml should refresh catalogs and trigger validation of opened XML files.

As configuring XML catalog is  so hard, I think it's an important task. I'm working on this issue.

**Comment by fbricon** [comment] 2018-11-09 16:20
Closing as duplicate of #143

**Comment by angelozerr** [comment] 2018-11-09 17:17
@fbricon I reopen it because it's not the same feature than https://github.com/angelozerr/lsp4xml/issues/143

Indeed this issue is when you save a XML catalog file and when you change the XML catalog settings (settings.json in vscode).

**Comment by angelozerr** [comment] 2018-11-09 17:21
@fbricon I have implemented a save support action. We will able to to use to implement #143

Here a demo:

![212](https://user-images.githubusercontent.com/1932211/48277857-2c7f7c80-e44c-11e8-9eef-a9bad05f71cf.gif)

@ralfhandl I think this feature could interest you. Hope it will work for you.

**Comment by angelozerr** [comment] 2018-11-09 17:22
I close issue,if you it doesn't work, please reopen it.

**Closed** 2018-11-09 17:22 UTC
Labels: catalog, duplicate, enhancement, validation
