### ISSUE TITLE
Duplicate suggestions

### ISSUE THREAD

**Issue by felixfbecker** [angelozerr/lsp4xml#125] opened 2018-09-14 16:17 UTC
![image](https://user-images.githubusercontent.com/10532611/45562262-2f922e00-b84a-11e8-88f3-4fc64c91c375.png)

Noteworthy is that one `Name` suggestion shows docs, the other doesn't. Looks like one is inferred from the existing `Name` tag.
Expected would be 0 suggestions for `Name`, because `Name` must only appear once.

Schema is here: https://github.com/felixfbecker/PowerShellXSD/blob/master/Types.xsd

Relevant section:
```xml
<xs:complexType name="Type">
    <xs:sequence>
      <xs:element name="Name" type="xs:string">
        <xs:annotation>
          <xs:documentation>A pair of `&lt;Name&gt;` tags that enclose the name of the affected .NET Framework type.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="Members" type="Members" />
      <xs:element minOccurs="0" name="TypeConverter" type="TypeConverter" />
      <xs:element minOccurs="0" name="TypeAdapter" type="TypeAdapter" />
    </xs:sequence>
  </xs:complexType>
```

**Comment by angelozerr** [comment] 2018-09-25 13:36
I cannot reproduce it.

**Comment by angelozerr** [comment] 2018-09-26 00:57
@felixfbecker please close it, if problem is gone.

**Comment by angelozerr** [comment] 2018-09-28 17:36
I close it, if you have a problem again, please reopen it.

**Closed by angelozerr** 2018-09-28 17:36 UTC

**Comment by felixfbecker** [comment] 2018-10-08 09:56
I am still seeing this:

![image](https://user-images.githubusercontent.com/10532611/46602678-21ee6200-caf1-11e8-8e70-5cde6c50ec28.png)

**Comment by angelozerr** [comment] 2018-10-08 10:49
I cannot reproduce with Eclipse LSP4e -( @NikolasKomonen have you the same problem than @felixfbecker ?
