### ISSUE TITLE
Outline for DTD file is messed up

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#226] opened 2018-11-14 19:33 UTC
Save http://java.sun.com/dtd/web-app_2_3.dtd locally and open it, you'll see the outline view and breadcrumbs (if "breadcrumbs.enabled": true) look really bad:
<img width="1437" alt="screen shot 2018-11-14 at 2 25 29 pm" src="https://user-images.githubusercontent.com/148698/48507396-d3339680-e819-11e8-809a-2eaba28c632e.png">

**Comment by angelozerr** [comment] 2018-11-14 21:00
https://github.com/angelozerr/lsp4xml/issues/228 should fix that

**Comment by angelozerr** [comment] 2018-11-25 20:04
@fbricon I have started to manage DTD ElementDecl and attributes witth teh DOMDocument. Outline should now display DTD <!ELEMENT and <!ATTLIST (external or intenal DTD should work).

For external DTD, I display the DOCTYPE, because external DTD is a DOMDOcument which have only a DOMDocumentType (it's a choice that I have done to continue to work with DOMDocument only, and not have a new structure like DTDDocument))

@NikolasKomonen, @fbricon hope you will like it. Tests must be written.

**Comment by fbricon** [comment] 2018-11-25 22:15
This is indeed much better. But I think AttList support still need some love:

<img width="1024" alt="screen shot 2018-11-25 at 5 14 40 pm" src="https://user-images.githubusercontent.com/148698/48985460-bf1f4d00-f0d5-11e8-86de-3ae43ec3643f.png">

**Comment by fbricon** [comment] 2018-11-25 22:18
mmm WTP chose to not even display AttList elements in its outline

**Comment by angelozerr** [comment] 2018-11-30 18:33
@fbricon I wanted to display attribute in hierarchy (I have coded that), but it seems teh hierarchy doesn't use the "containerName". It seems it uses location, so it's not possible to display attributes after a given element as a tree. That's why I display attribute with element@attribute label.

Any feedback are welcome!

**Comment by fbricon** [comment] 2018-11-30 18:41
do you have a new screenshot?

**Comment by angelozerr** [comment] 2018-11-30 18:53
I will do it if you wish, but you can try it. I have pushed my work.

**Comment by fbricon** [comment] 2018-11-30 18:54
Sorry I can't play with lsp4xml today

**Comment by angelozerr** [comment] 2018-12-01 14:58
Here the result in vscode:

![image](https://user-images.githubusercontent.com/1932211/49329609-d2249800-f581-11e8-815b-c982bbc0e8f3.png)

Please note that you must use vscode-xml 0.2.0 to test it with lsp4xml from master because if https://github.com/redhat-developer/vscode-xml/issues/94

**Comment by fbricon** [comment] 2018-12-04 21:20
- The ordering is completely random, I'd expect it to follow either the alphabetical order, or positions, or elements then attlist, anything really. This is unsettling.
- atllist and elements should have different SymbolKinds, so they can be distinguished visually

**Comment by angelozerr** [comment] 2018-12-05 00:18
> The ordering is completely random, I'd expect it to follow either the alphabetical order, or positions, or elements then attlist, anything really. This is unsettling.

I think you have your Outline vscode sorted by type, no? Sort by location or name should fix your sort, no?

> atllist and elements should have different SymbolKinds, so they can be distinguished visually

fixed.

I have written tests too, so if you think we can close this issue, close it. thanks.

**Comment by jrieken** [comment] 2018-12-05 08:03
what does "outline > ... > sort by" say?

**Comment by angelozerr** [comment] 2018-12-05 08:10
@fbricon as I tried to explain you and @jrieken suggest you, I think it's your preferences of your outline which is sorted by type I think:

![image](https://user-images.githubusercontent.com/1932211/49499153-8fa6d800-f86d-11e8-906c-2f9358f7d1b6.png)

**Comment by fbricon** [comment] 2018-12-05 13:44
@angelozerr @jrieken ok it was sorted by type. Which I suspected. I completely overlooked that menu. It's just that the secondary sort seems unpredictable, but that looks like a VS Code thing. 
Anyways, there's nothing more to do on the server side I think.

**Comment by jrieken** [comment] 2018-12-05 14:04
> secondary sort seems unpredictable, but that looks like a VS Code thing.

Yeah, we have issue for that on our end. 🤞 that we fix that next milestone...

**Comment by fbricon** [comment] 2018-12-10 15:43
Outline is still borked with this [dtd](http://www.cs.washington.edu/research/projects/xmltk/xmldata/data/nasa/dataset_053.dtd) :
<img width="1381" alt="screen shot 2018-12-10 at 10 39 34 am" src="https://user-images.githubusercontent.com/148698/49743150-21e11e80-fc68-11e8-8fe2-a85649eb6deb.png">

**Comment by fbricon** [comment] 2018-12-10 15:53
Also ATTLIST seem to be lost when elements have the same name, in  http://java.sun.com/dtd/web-app_2_3.dtd : 
> <!ATTLIST auth-constraint id ID #IMPLIED>
> <!ELEMENT auth-constraint (description?, role-name*)>

probably because it's the same symbol type

**Comment by angelozerr** [comment] 2018-12-10 16:02
@fbricon I think the problem is because XMLScanner is not enough tolerant. I hope @NikolasKomonen work in https://github.com/angelozerr/lsp4xml/pull/261 will improve that.

As I try to explain we need a really more tolerant parser. @NikolasKomonen it should be cool if you could see if your https://github.com/angelozerr/lsp4xml/pull/261 fixes the problem and otherwise try to fix it. If you have no time, I will see it.

**Comment by fbricon** [comment] 2018-12-10 16:05
@angelozerr the dtd's are not malformed, so it's not (only) a matter of being fault tolerant or not.
I get the same problem when applying #261

**Comment by angelozerr** [comment] 2018-12-10 16:08
@fbricon it's because our parser desn't take care of possibility of ATTLIST parsing. The problem comes from 

```
<!ATTLIST dataset
	xmlns:xlink CDATA #FIXED "http://www.w3.org/XML/XLink/0.9"
	subject CDATA "astronomy"
>
```

Our dtd parser consider that this ATTLIST is not valid (althoug it is valid). So we need 2 fixes:

 * the first fix is to become more tolerant (even if our parser cannot parsed it, it must not break the other content)
 * the second fix is to parse correctly this ATTLIST

**Comment by fbricon** [comment] 2018-12-10 16:08
> Also ATTLIST seem to be lost when elements have the same name, in http://java.sun.com/dtd/web-app_2_3.dtd :
> 
> ```
> <!ATTLIST auth-constraint id ID #IMPLIED>
> <!ELEMENT auth-constraint (description?, role-name*)>
> ```
> probably because it's the same symbol type

Ok so now I see that ATTLIST are shown as children of ELEMENTs. So that's ok.

**Comment by angelozerr** [comment] 2018-12-10 16:10
In other words, it's not a problem with outline (XML DocumentSymbol provider), but a problem with XML Scanner. In other words it's the issue https://github.com/angelozerr/lsp4xml/issues/231

Outline shows the problem but it's not the outline which must be fixed, it's the XMLScanner (issue https://github.com/angelozerr/lsp4xml/issues/231)

**Closed** 2019-01-09 16:57 UTC
Labels: DTD, bug, symbols
